# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.author.email, 'burce-ci@gmail.com')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run coverage

      - name: Display event name
        run: echo "github.event.head_commit.author.email=${{ github.event.head_commit.author.email }}"

      - run: npm ci
      - run: npm coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ArthurYung/keeper

      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}
