# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.author.name, 'GitHub Action')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: node benchmark/index.js
      - run: |
          git config --local user.email "bruceau00@gmail.com"
          git config --local user.name "GitHub Action"
      - run: echo "npm token=${{secrets.NPM_TOKEN}}"
      - run: npm run version
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - run: git push --follow-tags origin master
